import Head from 'next/head';
import Image from 'next/image';
import { Inter } from '@next/font/google';
import styles from '@/styles/Home.module.css';
import Link from 'next/link';
import { useState } from 'react';
import { useSession, getSession, signOut } from 'next-auth/react';

export default function Home() {
  const { data: session } = useSession();

  function handleSignOut() {
    signOut();
  }

  return (
    <>
      <Head>
        <title>Sign In</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* {Guest()} */}
      {session ? User({ session, handleSignOut }) : Guest()}
    </>
  );
}

const Guest = () => {
  return (
    <main className={styles.main__item}>
      <h1>Welcome Guest user</h1>
      <div className={styles.signin__button}>
        <Link href={'/signin'} legacyBehavior>
          <a href="">Sign In</a>
        </Link>
      </div>
    </main>
  );
};
const User = ({ session, handleSignOut }) => {
  return (
    <main className={styles.main__item}>
      <h1 className={styles.authh1}>Welcome {session.user.name}</h1>
      <p className={styles.auth_p}>
        your sign In email id is{'  '}
        <span className={styles.authemail}>{session.user.email}</span>
      </p>

      <div className={styles.signin__button}>
        <button onClick={handleSignOut}>
          <span>Sign Out</span>
        </button>
      </div>
    </main>
  );
};

// export async function getServerSideProps({ req }) {
//   const session = await getSession({ req });

//   if (!session) {
//     return {
//       redirect: {
//         destination: '/login',
//         permanent: false,
//       },
//     };
//   }
//   return {
//     props: { session },
//   };
// }
